### ISSUE TITLE
Run single-process benchmark vs Apache Spark

### ISSUE THREAD

**Issue by andygrove** [datafusion-rs/datafusion-rs#25]
For the first benchmark, I'm thinking that a geospatial use case would be good. It would be easy to generate csv files of varying size contianing fake address data and lat/lng co-ordinates and then run a job to translate the lat/lngs to quadkeys or mercator projection.

References:

- https://msdn.microsoft.com/en-us/library/bb259689.aspx
- https://wiki.openstreetmap.org/wiki/Mercator#JavaScript_.28or_ActionScript.29

**Comment by maccam912** [comment]
I have a commit here to start adding some benchmarking via [criterion.rs](https://github.com/japaric/criterion.rs). Would you like a PR for it?

 https://github.com/maccam912/datafusion-rs/commit/33fb58758a06bd16023ea2c3b4a157a5809215c5

**Comment by andygrove** [comment]
That would be awesome! ty

I hadn't heard about criterion.rs before ... looks very interesting

**Comment by andygrove** [comment]
Initial benchmark was published: https://andygrove.io/2018/03/datafusion-0.2.1-benchmark/
